// *************************************************************
// *  Do NOT edit this file inside Google apps script editor!  *
// *  https://github.com/vladimyr/ee-summercamp-gapps-script   *
// *************************************************************

/* eslint-disable no-unused-vars */
/* global Environment, PropertiesService, UrlFetchApp, Utilities */

var props = PropertiesService.getScriptProperties();

function env(name) {
  return Environment[name] || props.getProperty(name);
}

function githubUrl() {
  var args = [].slice.call(arguments, 0);
  args.unshift('https://api.github.com');
  args = args.map(function (arg) {
    return arg.replace(/^\/+|\/+$/g, '');
  });
  return args.join('/');
}

function githubHeaders(githubToken) {
  var authorization = Utilities.formatString('token %s', githubToken);
  return {
    authorization: authorization,
    accept: 'application/vnd.github.v3+json',
    'user-agent': 'https://github.com/vladimyr/ee-summercamp-gapps-script'
  };
}

function githubFetch(url, githubToken) {
  var headers = githubHeaders(githubToken);
  var resp = UrlFetchApp.fetch(url, { headers: headers });
  return JSON.parse(resp.getContentText());
}

function getUserRepos(username, githubToken) {
  var url = githubUrl('users', username, 'repos');
  return githubFetch(url, githubToken);
}

function getRepoContents(username, repo, githubToken) {
  var url = githubUrl('repos', username, repo, 'contents');
  return githubFetch(url, githubToken);
}

/**
 * Check if user has target repo (e.g. 'ee-summercamp-2019')
 * @param {string} username Github username
 * @returns {boolean} boolean result
 * @customfunction
 */
function checkGithub(username) {
  if (!username) return false;
  if (username.map) {
    return username.map(checkGithub);
  }
  var githubToken = env('GITHUB_API_TOKEN');
  var repoPattern = Utilities.formatString('^%s$', env('GITHUB_REPO_PATTERN'));
  var reRepoName = new RegExp(repoPattern, 'i');
  var repos = getUserRepos(username, githubToken);
  var match = repos.find(function (repo) {
    return reRepoName.test(repo.name.trim());
  });
  return Boolean(match);
}
